import { AiFillStar } from "react-icons/ai";

const data = [
  {
    img: "https://m.media-amazon.com/images/I/61cG9RGN9xL._SY450_.jpg",
    title: "HONOR Pad X9 11.5-inch (29.21 cm)",
    star: 4,
    reviews: "(1053 ratings)",
    prevPrice: "25999",
    newPrice: "12999",
    company: "Honor",
    color: "grey",
    category: "tablets"
  },
  {
    img: "https://m.media-amazon.com/images/I/41Qg6YkjaEL._SY355_.jpg",
    title: "boAt BassHeads 100 Wired with Mic",
    star: 5,
    reviews: "(245864 ratings)",
    prevPrice: "999",
    newPrice: "328",
    company: "boAt",
    color: "black",
    category: "headphones"
  },
  {
    img: "https://m.media-amazon.com/images/I/71scmEdSC2L._SX569_.jpg",
    title: "Redmi 13C Starfrost White",
    star: 4,
    reviews: "(23704 ratings)",
    prevPrice: "13999",
    newPrice: "8498",
    company: "Redmi",
    color: "white",
    category: "smartphones"
  },
  {
    img: "https://m.media-amazon.com/images/I/71czGb00k5L._SY450_.jpg",
    title: "Acer Aspire Lite 12th Gen Intel Core i3",
    star: 4,
    reviews: "(957 ratings)",
    prevPrice: "52990",
    newPrice: "29990",
    company: "Acer",
    color: "grey",
    category: "laptops"
  },
  {
    img: "https://m.media-amazon.com/images/I/71i6-yYY1IL._SY355_.jpg",
    title: "boAt Airdopes 141 Bluetooth TWS",
    star: 3,
    reviews: "(204341 ratings)",
    prevPrice: "4490",
    newPrice: "1249",
    company: "boAt",
    color: "green",
    category: "headphones"
  },
  {
    img: "https://m.media-amazon.com/images/I/71m+dNHzoGL._SX569_.jpg",
    title: "Motorola Edge 50 Fusion 5G Pink",
    star: 4,
    reviews: "(65 ratings)",
    prevPrice: "27999",
    newPrice: "25815",
    company: "Motorola",
    color: "pink",
    category: "smartphones"
  },
  {
    img: "https://m.media-amazon.com/images/I/51PVcR9nQPL._SX679_.jpg",
    title: "Lenovo Tab4 10 Tablet",
    star: 3,
    reviews: "(1800 ratings)",
    prevPrice: "8999",
    newPrice: "6550",
    company: "Lenovo",
    color: "black",
    category: "tablets"
  },
  {
    img: "https://m.media-amazon.com/images/I/61shfvVhxjL._SY355_.jpg",
    title: "boAt Rockerz 255 Touch Neckband",
    star: 5,
    reviews: "(199249 ratings)",
    prevPrice: "4999",
    newPrice: "1299",
    company: "boAt",
    color: "blue",
    category: "headphones"
  },
  {
    img: "https://m.media-amazon.com/images/I/41nRYrr3FGL._SX300_SY300_QL70_FMwebp_.jpg",
    title: "realme NARZO 70 Pro 5G",
    star: 3,
    reviews: "(4312 ratings)",
    prevPrice: "26999",
    newPrice: "18248",
    company: "realme",
    color: "green",
    category: "smartphones"
  },
  {
    img: "https://m.media-amazon.com/images/I/71jG+e7roXL._SX522_.jpg",
    title: "Apple MacBook Air Laptop",
    star: 4,
    reviews: "(4869 ratings)",
    prevPrice: "92900",
    newPrice: "62990",
    company: "Apple",
    color: "white",
    category: "laptops"
  },
  {
    img: "https://m.media-amazon.com/images/I/51+e7yrgPpL._SY355_.jpg",
    title: "Noise Buds VS104 TWS",
    star: 5,
    reviews: "(29675 ratings)",
    prevPrice: "3499",
    newPrice: "1299",
    company: "Noise",
    color: "green",
    category: "headphones"
  },
  {
    img: "https://m.media-amazon.com/images/I/41GAnuY2-DL._SX300_SY300_QL70_FMwebp_.jpg",
    title: "Samsung Galaxy S23 Ultra 5G AI Phone",
    star: 4,
    reviews: "(1406 ratings)",
    prevPrice: "149999",
    newPrice: "84999",
    company: "Samsung",
    color: "green",
    category: "smartphones"
  },
  {
    img: "https://m.media-amazon.com/images/I/81epBowa4UL._SX450_.jpg",
    title: "Lenovo IdeaPad Slim 3 Intel Core i7",
    star: 3,
    reviews: "(513 ratings)",
    prevPrice: "85390",
    newPrice: "64990",
    company: "Lenovo",
    color: "grey",
    category: "laptops"
  },
  {
    img: "https://m.media-amazon.com/images/I/61+5q4oGJWL._SY355_.jpg",
    title: "ZEBRONICS Zeb-Bro Wired Earphones",
    star: 4,
    reviews: "(52445 ratings)",
    prevPrice: "399",
    newPrice: "159",
    company: "ZEBRONICS",
    color: "blue",
    category: "headphones"
  },
  {
    img: "https://m.media-amazon.com/images/I/710WMfH99HL._SY450_.jpg",
    title: "Redmi Pad SE 8GB, 128GB Tablet",
    star: 3,
    reviews: "(427 ratings)",
    prevPrice: "19999",
    newPrice: "14999",
    company: "Redmi",
    color: "grey",
    category: "tablets"
  },
  {
    img: "https://m.media-amazon.com/images/I/61SmnheBBRL._SX569_.jpg",
    title: "Redmi 12 5G Moonstone Silver",
    star: 4,
    reviews: "(23704 ratings)",
    prevPrice: "19999",
    newPrice: "13999",
    company: "Redmi",
    color: "grey",
    category: "smartphones"
  },
  {
    img: "https://m.media-amazon.com/images/I/51aXvjzcukL._SY355_.jpg",
    title: "Sony WH-1000XM5 Over Ear Headphone",
    star: 5,
    reviews: "(13885 ratings)",
    prevPrice: "34990",
    newPrice: "29984",
    company: "Sony",
    color: "black",
    category: "headphones"
  },
  {
    img: "https://m.media-amazon.com/images/I/715Dsu2jxWL._SX450_.jpg",
    title: "Samsung Galaxy Tab S6 Lite(10.4 Inch)",
    star: 3,
    reviews: "(2754 ratings)",
    prevPrice: "30999",
    newPrice: "20999",
    company: "Samsung",
    color: "grey",
    category: "tablets"
  },
  {
    img: "https://m.media-amazon.com/images/I/51V2OoArdZL._SY450_.jpg",
    title: "Dell [Smartchoice]15 Thin & Light Laptop",
    star: 3,
    reviews: "(665 ratings)",
    prevPrice: "47876",
    newPrice: "35990",
    company: "Dell",
    color: "black",
    category: "laptops"
  },
  {
    img: "https://m.media-amazon.com/images/I/61YP3nZAptL._SX355_.jpg",
    title: "Samsung Galaxy Buds2 Pro",
    star: 4,
    reviews: "(8146 ratings)",
    prevPrice: "19999",
    newPrice: "7999",
    company: "Samsung",
    color: "white",
    category: "headphones"
  },
  {
    img: "https://m.media-amazon.com/images/I/41NOKPCVM7L._SX300_SY300_QL70_FMwebp_.jpg",
    title: "OnePlus Nord CE 3 Lite 5G",
    star: 2,
    reviews: "(50198 ratings)",
    prevPrice: "19999",
    newPrice: "16669",
    company: "OnePlus",
    color: "grey",
    category: "smartphones"
  },
  {
    img: "https://m.media-amazon.com/images/I/71QT9PrfxyL._SX466_.jpg",
    title: "Apple AirPods (2nd Generation) Case",
    star: 3,
    reviews: "(13878 ratings)",
    prevPrice: "14900",
    newPrice: "10900",
    company: "Apple",
    color: "white",
    category: "headphones"
  },
  {
    img: "https://m.media-amazon.com/images/I/81XXj6IKM8L._SX569_.jpg",
    title: "Samsung Galaxy M35 5G",
    star: 4,
    reviews: "(1519 ratings)",
    prevPrice: "24499",
    newPrice: "19999",
    company: "Samsung",
    color: "grey",
    category: "smartphones"
  },
  {
    img: "https://m.media-amazon.com/images/I/71Got5ZZBLL._SY450_.jpg",
    title: "ASUS Vivobook Go 15 (2023)",
    star: 3,
    reviews: "(112 ratings)",
    prevPrice: "70990",
    newPrice: "39990",
    company: "Asus",
    color: "black",
    category: "laptops"
  },
  {
    img: "https://m.media-amazon.com/images/I/61bK6PMOC3L._SX522_.jpg",
    title: "Apple iPhone 14 (128 GB) - Blue",
    star: 4,
    reviews: "(5540 ratings)",
    prevPrice: "69900",
    newPrice: "55900",
    company: "Apple",
    color: "blue",
    category: "smartphones"
  },
  {
    img: "https://m.media-amazon.com/images/I/71f32PhZhpL._SX522_.jpg",
    title: "Apple iPad Air 11″ (M2)",
    star: 2,
    reviews: "(85 ratings)",
    prevPrice: "69900",
    newPrice: "59900",
    company: "Apple",
    color: "grey",
    category: "tablets"
  },
  {
    img: "https://m.media-amazon.com/images/I/61LpL+cBZYL._SY450_.jpg",
    title: "HP Pavilion 14 12th Gen Intel Core i7",
    star: 4,
    reviews: "(757 ratings)",
    prevPrice: "93261",
    newPrice: "76990",
    company: "HP",
    color: "silver",
    category: "laptops"
  },
  {
    img: "https://m.media-amazon.com/images/I/61e+AB+vO1L._SX425_.jpg",
    title: "JBL Newly Launched Wave Flex TWS",
    star: 4,
    reviews: "(194 ratings)",
    prevPrice: "4999",
    newPrice: "2699",
    company: "JBL",
    color: "green",
    category: "headphones"
  },
  {
    img: "https://m.media-amazon.com/images/I/81Os1SDWpcL._SX522_.jpg",
    title: "Apple iPhone 15 Pro Max (256 GB) - Black ",
    star: 5,
    reviews: "(343 ratings)",
    prevPrice: "159900",
    newPrice: "140999",
    company: "Apple",
    color: "black",
    category: "smartphones"
  },
  {
    img: "https://m.media-amazon.com/images/I/61-r9zOKBCL._SX522_.jpg",
    title: "Apple iPhone 13 (128GB) - Green",
    star: 4,
    reviews: "(29116 ratings)",
    prevPrice: "59900",
    newPrice: "49900",
    company: "Apple",
    color: "green",
    category: "smartphones"
  },
  {
    img: "https://m.media-amazon.com/images/I/31u+KjpAvKL._SX466_.jpg",
    title: "Apple EarPods Wired (USB-C) ",
    star: 3,
    reviews: "(10 ratings)",
    prevPrice: "2000",
    newPrice: "1649",
    company: "Apple",
    color: "white",
    category: "headphones"
  },
  {
    img: "https://m.media-amazon.com/images/I/71Qo8wRrWhL._SY450_.jpg",
    title: "HP Victus Gaming Laptop",
    star: 5,
    reviews: "(37 ratings)",
    prevPrice: "78778",
    newPrice: "58841",
    company: "HP",
    color: "blue",
    category: "laptops"
  },
  {
    img: "https://m.media-amazon.com/images/I/81vqHyDCSCL._SX466_.jpg",
    title: "Samsung Galaxy S21 FE 5G",
    star: 4,
    reviews: "(1338 ratings)",
    prevPrice: "74999",
    newPrice: "28999",
    company: "Samsung",
    color: "black",
    category: "smartphones"
  },
  {
    img: "https://m.media-amazon.com/images/I/61uA2UVnYWL._SX522_.jpg",
    title: "Apple iPad (10th Generation)",
    star: 4,
    reviews: "(1540 ratings)",
    prevPrice: "44900",
    newPrice: "30999",
    company: "Apple",
    color: "blue",
    category: "tablets"
  },
  {
    img: "https://m.media-amazon.com/images/I/71LPoR+xsgL._SY450_.jpg",
    title: "Samsung Galaxy Book4 ",
    star: 1,
    reviews: "(0 ratings)",
    prevPrice: "91989",
    newPrice: "68718",
    company: "Samsung",
    color: "grey",
    category: "laptops"
  },
  {
    img: "https://m.media-amazon.com/images/I/71wkgHCzagL._SY450_.jpg",
    title: "Redmi Pad Pro 5G Graphite Grey",
    star: 4,
    reviews: "(110 ratings)",
    prevPrice: "27999",
    newPrice: "24999",
    company: "Redmi",
    color: "grey",
    category: "tablets"
  },
  {
    img: "https://m.media-amazon.com/images/I/71aBAPCVc8L._SY355_.jpg",
    title: "Boult Audio UFO TWS ",
    star: 5,
    reviews: "(7917 ratings)",
    prevPrice: "3499",
    newPrice: "1299",
    company: "Boult",
    color: "white",
    category: "headphones"
  },
  {
    img: "https://m.media-amazon.com/images/I/71ItMeqpN3L._SX522_.jpg",
    title: "Apple 2024 MacBook Air 13″ Laptop",
    star: 5,
    reviews: "(69 ratings)",
    prevPrice: "114900",
    newPrice: "109155",
    company: "Apple",
    color: "grey",
    category: "laptops"
  },
];

export default data;